---
title: "binoculaR"
output: 
  html_document:
    self_contained: no
---

```{r setup, include = F}
knitr::opts_chunk$set(
  echo = T,
  eval = T,
  warning = F,
  message = F,
  error = F,
  tidy = F,
  collapse = T,
  comment = "#>"
  #fig.path = "inst/assets/README_files/figure-markdown_github",
  #screenshot.force = params$escape_script # When script is not dynamic (markdown) we should use screenshots.
)
```

# Data

## Loading 

```{r}
# library(haven)
# ess <- read_spss("https://github.com/systats/binoculaR/raw/master/data/ess_round8.sav")
rm(list=ls())
load("data/ess.Rdata")
```


## Inspecting

```{r}
# devtools::install_github("systats/binoculaR", force = T)
# selected <- binoculaR::binoculaR(ess)
# save(selected, file = "data/vars.Rdata")
load("data/vars.Rdata")
```


## Subsetting

```{r}
library(dplyr)
ess_sub <- ess %>%
  select(selected$index)

# binoculaR::binoculaR(ess_sub)
```


```{r}
library(dplyr)
library(countrycode)
glimpse(ess_sub)

ess_work <- ess_sub %>%
  mutate_if(.predicate = is.double, .funs = as.numeric) %>%
  mutate_if(.predicate = is.character, .funs = as.character) %>%
  mutate(
    region = 
      countrycode(
        sourcevar = cntry, 
        origin = "iso2c", 
        destination = "country.name.en"
      )
  ) %>%
  mutate(EU_accession = 
           recode_factor(region, 
                Belgium = 1958,
                Germany = 1958,  
                Belgium = 1958,
                France = 1958,
                Netherlands = 1958,
                Ireland = 1973,
                `United Kingdom of Great Britain and Northern Ireland` = 1973,
                Finland = 1995,
                Austria = 1995,
                Sweden = 1995,
                Estonia = 2004,
                Poland = 2004,
                Slovenia = 2004,
                `Czech Republic` = 2004,
                Switzerland = 0,
                Israel = 0,
                Iceland = 0,
                Norway = 0,
                `Russian Federation` = 0
              )
        ) %>%
  mutate(pc = ifelse(region %in% c("Estonia", "Poland", "Slovenia", "Czech Republic", "Russian Federation"), "Post-Communist", "West"))

glimpse(ess_work)
```


```{r, eval = F}
library(ggplot2)
library(viridis)
library(ggthemes)

europe <- ggplot2::map_data('world', region = unique(ess_work$region))

map_data <- ess_work %>%
  select(region, imwbcnt) %>%
  group_by(region) %>%
  summarise(value = mean(imwbcnt, na.rm = T)) %>%
  dplyr::left_join(europe)

library(ggthemes)
map_data %>% 
  ggplot(aes(x = long, y = lat, group = group)) +
    geom_polygon(aes(text = region, fill = value), alpha = .7) + 
    theme_map() +
    coord_map(xlim=c(-23, 45),  ylim=c(32, 71)) + 
    scale_fill_viridis(option = "A") +
    ggtitle(label = selected$var_names[selected$var_codes %in% "imwbcnt"])

plotly::ggplotly()
```

> If the pipe ( %>% in 2014) had been invented before, ggplot2 would have never existed - Hadley Wickham

* https://lsru.github.io/tv_course/lecture07_plotting.html#9

```{r, eval = F}
library(ggplot2)
library(forcats)
library(ggthemes)
library(ggridges)
library(gridExtra)

gg1 <- ess_work %>%
  group_by(region) %>%
  mutate(value = mean(imwbcnt, na.rm = T)) %>% 
  ggplot(aes(fct_reorder(cntry, value), imwbcnt, colour = pc)) +
  geom_jitter(alpha = .5, size = .5) + 
  geom_boxplot(fill = NA, color = "black") +
  labs(x = NULL) +
  theme(legend.position = "none")

gg2 <- ess_work %>%
  filter(edulvlb < 5000) %>%
  ggplot(aes(edulvlb, imwbcnt, colour = pc)) +
  geom_jitter(width = 50, alpha = .05, size = 2) +
  geom_smooth(method = "lm", se = F) +
  geom_smooth() +
  theme_bw() +
  theme(legend.position = "none") 

gg3 <- ess_work %>%
  ggplot(aes(y = cntry, x = rlgdgr, fill = pc)) + 
  geom_density_ridges(scale = 2, size = 1, colour = NA, alpha = .5) +
  theme(legend.position = "none")

lay <- rbind(c(1, 2, 2),
             c(1, 3, 3))

grid.arrange(gg3, gg1, gg2, layout_matrix = lay)
```

## ggthemr

```{r, eval = F}
library(ggplot2)
library(forcats)
library(ggthemes)
library(ggridges)
library(gridExtra)
library(ggthemr)
 
ggthemr_set <- c("flat", "flat dark", "copper", "camoflauge", "chalk", "copper", "dust", "earth", "fresh", "grape", "grass", "greyscale", "light", "lilac", "pale", "sea", "sky", "solarized")

for(jj in 18:length(ggthemr_set)){
  ggthemr(ggthemr_set[jj], layout = 'scientific', spacing = 2, type = 'inner')
  
  #ggsave(grid, file = paste0("images/pal_", ggthemr_set[jj], ".png"), height = 1, width = 8)
  
  gg1 <- ess_work %>%
    group_by(region) %>%
    mutate(value = mean(imwbcnt, na.rm = T)) %>% 
    ggplot(aes(fct_reorder(cntry, value), imwbcnt, colour = pc)) +
    geom_jitter(alpha = .5, size = .5) + 
    geom_boxplot(fill = NA, color = "black") +
    labs(x = NULL, y = selected$var_names[selected$var_codes %in% "imwbcnt"]) +
    theme(legend.position = "none", text = element_text(size = 6))
  
  gg2 <- ess_work %>%
    filter(edulvlb < 5000) %>%
    ggplot(aes(edulvlb, imwbcnt, colour = pc)) +
    geom_jitter(width = 50, alpha = .05, size = 2) +
    geom_smooth(method = "lm", se = F) +
    labs(x = selected$var_names[selected$var_codes %in% "edulvlb"],
         y = "") +
    geom_smooth() +
    theme(legend.position = "none", text = element_text(size = 7))
  
  gg3 <- ess_work %>%
    ggplot(aes(y = cntry, x = rlgdgr, fill = pc)) + 
    geom_density_ridges(scale = 2, size = 1, colour = NA, alpha = .5) +
    theme(legend.position = "bottom", legend.direction = "horizontal", text = element_text(size = 7)) +   
    labs(x = selected$var_names[selected$var_codes %in% "rlgdgr"], y = "")
  
  nn <- 8
  if(jj == 4 | jj == 5 | jj == 11 | jj == 18) nn <- 6
  if(jj == 17) nn <- 5
  gg4 <- data.frame(cols = 1:nn %>% as.character()) %>%
    ggplot(aes(x = cols, fill = cols)) +
    geom_bar() +
    theme_map() +
    theme(legend.position = "none") +
    coord_fixed(ratio = 1) + 
    ggtitle(label = ggthemr_set[jj]) + 
    theme(title = element_text(size = 20))
  
  lay <- rbind(c(4, 2, 2),
               c(1, 2, 2),
               c(1, 2, 2),
               c(1, 3, 3),
               c(1, 3, 3),
               c(1, 3, 3))
  
  p <- grid.arrange(gg3, gg1, gg2, gg4, layout_matrix = lay)
  
  
  ggsave(p, filename = paste("images/ggthemr_",  jj, "_", ggthemr_set[jj], ".png", sep = ""), dpi=100)
  
  ggthemr::ggthemr_reset()
  cat(jj)
}
```

## ggthemes

```{r}
show_col(few_pal("light")(7))
```


```{r}
### build color palattes
library(ggplot2)
library(colorspace)

plot_palette <- function(cols){
  df <- data.frame(cols)
  
  library(dplyr)
  p <- df %>%
    ggplot(aes(x = cols, fill = cols)) +
    geom_bar() +
    theme_map() +
    theme(legend.position = "none") +
    coord_fixed(ratio = 1)
  
  return(p)
}

colours <- colorblind_pal()(8)
pal_colorblind <- plot_palette(cols = colours) + scale_fill_colorblind()
ggsave(pal_colorblind, file = "images/pal_colorblind.png", height = 1)

colours <- hc_pal()(8)
pal_hc <- plot_palette(cols = colours) + scale_fill_hc()
ggsave(pal_hc, file = "images/pal_hc.png", height = 1)

colours <- economist_pal()(8)
pal_eco <- plot_palette(cols = colours) + scale_fill_economist()
ggsave(pal_eco, file = "images/pal_eco.png", height = 1)

colours <- fivethirtyeight_pal()(3)
pal_fivethirtyeight <- plot_palette(cols = colours) + scale_fill_fivethirtyeight()
ggsave(pal_fivethirtyeight, file = "images/pal_fivethirtyeight.png", height = 1)

colours <- gdocs_pal()(8)
pal_gdocs <- plot_palette(cols = colours) + scale_fill_gdocs()
ggsave(pal_gdocs, file = "images/pal_gdocs.png", height = 1)

colours <- wsj_pal()(8)
pal_wsj <- plot_palette(cols = colours) + scale_fill_wsj()
ggsave(pal_wsj, file = "images/pal_wsj.png", height = 1)

colours <- solarized_pal()(8)
pal_solarized <- plot_palette(cols = colours) + scale_fill_wsj()
ggsave(pal_solarized, file = "images/pal_solarized.png", height = 1)

colours <- few_pal()(8)
pal_few <- plot_palette(cols = colours) + scale_fill_few()
ggsave(pal_few, file = "images/pal_few.png", height = 1)

colours <- few_pal()(8)
pal_calc <- plot_palette(cols = colours) + scale_fill_few()
ggsave(pal_calc, file = "images/pal_calc.png", height = 1)
```



```{r}
#### Examples
library(ggplot2)
library(forcats)
library(ggthemes)
library(ggridges)
library(gridExtra)

des_themes <- c("default", "economist", "economist_white", "fivethirtyeight", "gdocs", "hc", "wsj", "solarized", "few", "calc", "pander")

for(jj in 8:length(des_themes)){
  
  if(jj != 1) ggplot2::theme_set(eval(parse(text=paste0("theme_", des_themes[jj], "()"))))
  
  gg1 <- ess_work %>%
    group_by(region) %>%
    mutate(value = mean(imwbcnt, na.rm = T)) %>% 
    ggplot(aes(fct_reorder(cntry, value), imwbcnt, colour = pc)) +
    geom_jitter(alpha = .5, size = .5) + 
    geom_boxplot(fill = NA, color = "black") +
    labs(x = NULL, y = selected$var_names[selected$var_codes %in% "imwbcnt"]) +
    theme(legend.position = "none", text = element_text(size = 6))
  
  gg2 <- ess_work %>%
    filter(edulvlb < 5000) %>%
    ggplot(aes(edulvlb, imwbcnt, colour = pc)) +
    geom_jitter(width = 50, alpha = .05, size = 2) +
    geom_smooth(method = "lm", se = F) +
    labs(x = selected$var_names[selected$var_codes %in% "edulvlb"],
         y = "") +
    geom_smooth() +
    theme(legend.position = "none", text = element_text(size = 7))
  
  gg3 <- ess_work %>%
    ggplot(aes(y = cntry, x = rlgdgr, fill = pc)) + 
    geom_density_ridges(scale = 2, size = 1, colour = NA, alpha = .5) +
    theme(legend.position = "bottom", legend.direction = "horizontal", text = element_text(size = 7)) +   
    labs(x = selected$var_names[selected$var_codes %in% "rlgdgr"], y = "")

  gg4 <- plot_palette(cols = eval(parse(text=paste0(des_themes[2], "_pal()(8)")))) + ggtitle(label = des_themes[jj]) + theme(title = element_text(size = 20))
  
  if(jj == 2 | jj == 3){
    gg1 <- gg1 + scale_colour_economist()
    gg2 <- gg2 + scale_colour_economist()
    gg3 <- gg3 + scale_fill_economist()
    gg4 <- gg4 + scale_fill_economist()
  }
  if(jj == 4){
    gg1 <- gg1 + scale_colour_fivethirtyeight()
    gg2 <- gg2 + scale_colour_fivethirtyeight()
    gg3 <- gg3 + scale_fill_fivethirtyeight()
    gg4 <- gg4 + scale_fill_fivethirtyeight()
  }
  if(jj == 5){
    gg1 <- gg1 + scale_colour_gdocs()
    gg2 <- gg2 + scale_colour_gdocs()
    gg3 <- gg3 + scale_fill_gdocs()
    gg4 <- gg4 + scale_fill_gdocs()
  }
  if(F){
    gg1 <- gg1 + scale_colour_hc()
    gg2 <- gg2 + scale_colour_hc()
    gg3 <- gg3 + scale_fill_hc()
    gg4 <- gg4 + scale_fill_hc()
  }
  if(jj == 7){
    gg1 <- gg1 + scale_colour_wsj()
    gg2 <- gg2 + scale_colour_wsj()
    gg3 <- gg3 + scale_fill_wsj()
    gg4 <- gg4 + scale_fill_wsj()
  }
  if(jj == 8){
    gg1 <- gg1 + scale_colour_solarized()
    gg2 <- gg2 + scale_colour_solarized()
    gg3 <- gg3 + scale_fill_solarized()
    gg4 <- gg4 + scale_fill_solarized()
  }
  if(jj == 9){
    gg1 <- gg1 + scale_colour_few()
    gg2 <- gg2 + scale_colour_few()
    gg3 <- gg3 + scale_fill_few()
    gg4 <- gg4 + scale_fill_few()
  }
  if(jj == 10){
    gg1 <- gg1 + scale_colour_calc()
    gg2 <- gg2 + scale_colour_calc()
    gg3 <- gg3 + scale_fill_calc()
    gg4 <- gg4 + scale_fill_calc()
  }
  if(F){
    gg1 <- gg1 + scale_colour_pander()
    gg2 <- gg2 + scale_colour_pander()
    gg3 <- gg3 + scale_fill_pander()
    gg4 <- gg4 + scale_fill_pander()
  }
    
  lay <- rbind(c(4, 2, 2),
               c(1, 2, 2),
               c(1, 2, 2),
               c(1, 3, 3),
               c(1, 3, 3),
               c(1, 3, 3))
  
  p <- grid.arrange(gg3, gg1, gg2, gg4, layout_matrix = lay)
  
  ggsave(p, filename = paste("images/ggthemes_",  jj, "_", 
          des_themes[jj], ".png", sep = ""), width = 10, height = 7, dpi=100)
  cat(jj)
}

```

## ggtech

Install ggtech:

```{r, eval = F}
devtools::install_github("ricardo-bion/ggtech", dependencies=TRUE)
```

Tech themes and scales:

```{r, eval = F}
d + theme_tech(theme="airbnb") + 
  scale_fill_tech(theme="airbnb") + 
  labs(title="Airbnb theme", 
       subtitle="now with subtitles for ggplot2 >= 2.1.0")
```


```{r}
# devtools::install_github("ricardo-bion/ggtech", dependencies=TRUE)
# devtools::install_github("tidyverse/ggplot2")
library(ggplot2)
library(ggtech)
library(forcats)
library(ggridges)
#require(extrafont)
# need only do this once!
# font_import(pattern="[A/a]rial", prompt=FALSE)


tech_key = list(
  airbnb = c("#FF5A5F", "#FFB400", "#007A87", "#FFAA91", "#7B0051"), 
  facebook = c("#3b5998", "#6d84b4", "#afbdd4", "#d8dfea"), 
  google = c("#5380E4", "#E12A3C", "#FFBF03", "#00B723"), 
  etsy = c("#F14000", "#67B6C3", "#F0DA47", "#EBEBE6", "#D0D0CB"), 
  twitter = c("#55ACEE", "#292f33", "#8899a6", "#e1e8ed")
)

for(jj in 1:length(tech_key)){

  gg1 <- ess_work %>%
    group_by(region) %>%
    mutate(value = mean(imwbcnt, na.rm = T)) %>% 
    ggplot(aes(fct_reorder(cntry, value), imwbcnt, colour = pc)) +
    geom_jitter(alpha = .5, size = .5) + 
    geom_boxplot(fill = NA, color = "black") +
    labs(x = "", y = "") +
    ggtech::theme_tech(theme=names(tech_key)[jj]) + 
    theme(legend.position = "none", text = element_text(size = 9)) + 
    scale_colour_manual(values = tech_key[[jj]][1:2])
  
  
  gg2 <- ess_work %>%
    filter(edulvlb < 5000) %>%
    ggplot(aes(edulvlb, imwbcnt, colour = pc)) +
    geom_jitter(width = 50, alpha = .05, size = 2) +
    geom_smooth(method = "lm", se = F) +
    labs(x = selected$var_names[selected$var_codes %in% "edulvlb"], y = "") +
    geom_smooth() +
    ggtech::theme_tech(theme=names(tech_key)[jj]) + 
    theme(legend.position = "none", text = element_text(size = 7)) +
    scale_colour_manual(values = tech_key[[jj]][1:2])
  
  gg3 <- ess_work %>%
    ggplot(aes(y = cntry, x = rlgdgr, fill = pc)) + 
    geom_density_ridges(scale = 2, size = 1, colour = NA, alpha = .5) +
    labs(x = selected$var_names[selected$var_codes %in% "rlgdgr"], y = "") +
    ggtech::theme_tech(theme=names(tech_key)[jj]) + 
    theme(legend.position = "bottom", legend.direction = "horizontal", 
          text = element_text(size = 7)) +   
    scale_fill_tech(theme=names(tech_key)[jj]) 



  library(ggthemes)
  gg4 <- plot_palette(cols = 1:4 %>% as.character) + 
    ggtitle(label = names(tech_key)[jj]) + 
    theme_map() + 
    theme(legend.position = "none", title = element_text(size = 20)) + 
    scale_fill_manual(values = tech_key[[jj]][1:4]) 

  lay <- rbind(c(4, 2, 2),
                 c(1, 2, 2),
                 c(1, 2, 2),
                 c(1, 3, 3),
                 c(1, 3, 3),
                 c(1, 3, 3))
  library(gridExtra)
  p <- grid.arrange(gg3, gg1, gg2, gg4, layout_matrix = lay)
    
  ggsave(p, filename = paste("images/ggtech_",  jj, "_", 
            names(tech_key)[jj], ".png", sep = ""), width = 10, height = 7, dpi=70)
  
  cat(jj)

}
```

## hrbrthemes

```{r}
# devtools::install_github("hrbrmstr/hrbrthemes")
library(hrbrthemes)

gg1 <- ess_work %>%
    group_by(region) %>%
    mutate(value = mean(imwbcnt, na.rm = T)) %>% 
    ggplot(aes(fct_reorder(cntry, value), imwbcnt, colour = pc)) +
    geom_jitter(alpha = .5, size = .5) + 
    geom_boxplot(fill = NA, color = "black") +
    labs(x = "", y = "") +
    hrbrthemes::theme_ipsum() +
    hrbrthemes::scale_colour_ipsum() +
    theme(legend.position = "none", text = element_text(size = 9)) 

  gg2 <- ess_work %>%
    filter(edulvlb < 5000) %>%
    ggplot(aes(edulvlb, imwbcnt, colour = pc)) +
    geom_jitter(width = 50, alpha = .05, size = 2) +
    geom_smooth(method = "lm", se = F) +
    labs(x = selected$var_names[selected$var_codes %in% "edulvlb"], y = "") +
    geom_smooth() +
    hrbrthemes::theme_ipsum() +
    hrbrthemes::scale_colour_ipsum() +
    theme(legend.position = "none", text = element_text(size = 7)) 
  
  gg3 <- ess_work %>%
    ggplot(aes(y = cntry, x = rlgdgr, fill = pc)) + 
    geom_density_ridges(scale = 2, size = 1, colour = NA, alpha = .5) +
    labs(x = selected$var_names[selected$var_codes %in% "rlgdgr"], y = "") +
    hrbrthemes::theme_ipsum() +
    hrbrthemes::scale_fill_ipsum() +
    theme(legend.position = "bottom", legend.direction = "horizontal", 
          text = element_text(size = 7))



  library(ggthemes)
  gg4 <- plot_palette(cols = 1:4 %>% as.character) + 
    ggtitle(label = "ipsum") + 
    theme_map() + 
    theme(legend.position = "none", title = element_text(size = 20)) + 
    hrbrthemes::scale_fill_ipsum() 

  lay <- rbind(c(4, 2, 2),
                 c(1, 2, 2),
                 c(1, 2, 2),
                 c(1, 3, 3),
                 c(1, 3, 3),
                 c(1, 3, 3))
  library(gridExtra)
  p <- grid.arrange(gg3, gg1, gg2, gg4, layout_matrix = lay)
  # ggsave(p, filename = paste("images/hrbrthemes_", 
  #           "ipsum", ".png", sep = ""), width = 10, height = 7, dpi=70)
```


