---
title: "charts"
author: "Fabio Votta"
date: "27 November 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = F # Whether to cache results for future renders (efficient!)
                      , warning = F # Whether to display errors
                      , message = F # Whether to display messages
                      , error = F # mybe turn on
                      , tidy = F 
                      , fig.width = 10
                      , fig.height = 6
                      , fig.align = "center"
                      )
```

## R Data Simulation

```{r cars}
library(arm)
library(purrr)
library(MASS)
library(broom) 
library(ggthemes)
library(tidyverse)
library(ecodist)
library(viridis)
library(gridExtra)
library(grid)
library(lm.beta)
library(tidyr)
library(ggpubr)


generate_multi <- function(n, corseq){
  set.seed(2017)
  x <- runif(n, 1, 10)
#  corseq <- seq(0,.99,0.01)
  models <- list()
  std.models <- list()
  for (jj in seq_along(corseq)) {
    dat <- data.frame(corgen(x = x, r = corseq[jj],  epsilon = 0))
    colnames(dat) <- c("x1", "x2")
    dat$y <- 0.5 * dat$x1 + 0.5 * dat$x2 + rnorm(n, sd = 10)
    models[[jj]] <- tidy(lm(y ~ x1 + x2, data = dat))
    std.models[[jj]] <- data.frame(lm.beta::coef.lm.beta((lm.beta::lm.beta(lm(y ~ x1 + x2, data = dat)))))
    colnames(std.models[[jj]]) <- c("std.estimate")  
    models[[jj]] <- std.models[[jj]] %>% 
                      bind_cols(models[[jj]]) 
    models[[jj]]$cors <- corseq[jj]
#    cat(jj, "\n")
  }
  sim_dat <- bind_rows(models)
  sim_dat$col <- n
  return(sim_dat)
}

draw.data <- function(type, slope = 3, error = 8, n = 150){
  if(type=="linear.up"){
    x <- c(runif(n-2, 0, 4), 2, 2.1)
    y <- slope * x + rnorm(n, sd=error)
  }
  if(type=="linear.down"){
    x <- c(runif(n-2, 0, 4), 2, 2.1)
    y <- -slope * x + rnorm(n, sd=error)
  }
  if(type=="curved.up"){
    x <- c(runif(n-2, 0, 4), 2, 2.1)
    y <- slope * x^4 + rnorm(n, sd=error)
  }
  if(type=="curved.down"){
    x <- c(runif(n-2, 0, 4), 2, 2.1)
    y <- -slope * x^4 + rnorm(n, sd=error)
  }
  if(type=="curved.lowhigh"){
    x <- rep(1:100,1)
    y  <- slope * x + rnorm(n, sd = c(50:1, 1:50)*error) 
  }
  if(type=="fan.shaped"){
    x = seq(0,3.99,200/n)
    y = slope * x + rnorm(n, sd = sqrt(x^2.3))
  }
  if(type=="auto.corr"){
    x <- rep(1:100,1)
    intercept <- c(rep(c(1,3,6,9,12), each = 20))
    y  <- intercept + slope * x + rnorm(100, sd = 5) 
    return(data.frame(x=x,y=y,col=as.factor(intercept)))
  }
  if(type=="outlier"){
    x <- c(runif(n-2, 0, 4), 2, 2.1)
    y <- slope * x + rnorm(n, sd=error)
  }
  if(type=="cooksd"){
    x <- c(runif(n-2, 0, 4), 2, 2.1)
    y <- slope * x + rnorm(n, sd=error)
  }
  if(type=="exec1"){
    x = seq(0,3.99,200/n)
    y = slope * exp(x^2+20) + rnorm(n, sd = error^5)
  }
  if(type=="exec2"){
    x = seq(0,3.99,200/n)
    y = slope * -sqrt(exp(x^2+20)) - 23*x + rnorm(n, sd = exp(error))
  }
  if(type=="exec3"){
    x <- rep(1:100,1)
    y = slope * x + rnorm(n, sd = c(exp(0:1), sqrt(4:20))*error)
  }
  if(type=="exec4"){
    x <- rnorm(10000,2,1)
    y = slope * x + rnorm(n, sd = error)
  }
  if(type=="exec5"){
    x = seq(1000,2,-10/n)
    y = slope * -x + log(x) + rnorm(n, sd = sqrt(error))
  }
  if(type=="multicol"){
    corseq <- seq(0,.99,0.01)
    n <- seq(50, 3000, by = 500)
    sim.list <- list()
    for(jj in seq_along(n)) {
      sim.list[[jj]] <- generate_multi(n = n[jj], corseq)
      sim.list[[jj]]$n <- n[jj]
    } 
    sim_data <- bind_rows(sim.list)
    return(sim_data)
  }
  data.frame(x=x,y=y)
}

plot_it <- function(type, ...){
  dat <- draw.data(type = type, ...) %>% 
  lm(y ~ x, data = .) %>% 
  broom::augment() 

gg1 <- dat %>% 
  ggplot(aes(x,y)) + 
  geom_point(aes(color = y - .fitted)) +  
  scale_color_gradient2(low = "blue", mid = "lightgrey", high = "red") +
  guides(color = F, alpha = F) +  
  geom_segment(aes(x, y, 
                   xend = x, 
                   yend = .fitted), 
                   alpha = .05) +
  geom_smooth(method = "lm") +
  xlab("Unabhängige Variable X") + ylab("Unabhängige Variable Y") + 
  theme_minimal()

gg2 <- dat %>%
  ggplot(aes(x, .std.resid)) + 
  geom_point(aes(color = .std.resid)) +  
  scale_color_gradient2(low = "blue", mid = "lightgrey", high = "red") +
  guides(color = F, alpha = F) +
  geom_segment(aes(x, .std.resid,
                   xend = x, 
                   yend = 0), 
                   alpha = .05) +
  geom_smooth(method = "lm") +
  xlab("Unabhängige Variable X") + ylab("Standardisierte Residuen") + 
  theme_minimal()

if(type %in% c("curved.up", "curved.down")){
  gg1 <- gg1 + geom_smooth(method = "loess", color = "red")
  gg2 <- gg2 + geom_smooth(method = "loess", color = "red")
}


layout <- rbind(c(1,2), c(1,3))

gg3 <- dat %>%
  ggplot(aes(.std.resid)) +
  geom_histogram(aes(y = ..density..), 
                 fill="grey30", alpha = 0.2) +
  stat_function(fun = dnorm, lwd = 1, col = 'red') +
  xlab("Standardisierte Residuen") + ylab("Density") + 
  theme_minimal()

theplot <- gridExtra::grid.arrange(gg1, gg2, gg3,  
                                   layout_matrix = layout)
grid.draw(theplot)

}

plot_it2 <- function(type, method = "lm", outlierdata = NULL, ...){
  dat <- draw.data(type = type, ...)
  
  if(!is.null(outlierdata)){
    dat <- rbind(dat, outlierdata)
  }
  
  dat <- dat %>% 
    lm(y ~ x, data = .) %>% 
    broom::augment() 

  if(type %in% c("outlier")){
    
  gg1 <- dat %>% 
    ggplot(aes(x,y)) + 
    geom_point(aes(color = y - .fitted)) +  
    scale_color_gradient2(low = "blue", mid = "lightgrey", high = "red") +
    guides(color = F, alpha = F) +  
    geom_segment(aes(x, y, 
                     xend = x, 
                     yend = .fitted), 
                     alpha = .05) +
    geom_smooth(method = "lm") +
    xlab("Unabhängige Variable X") + ylab("Unabhängige Variable Y") + 
    theme_minimal()
  } else{
  if(type %in% c("cooksd")){
    
  gg1 <- dat %>%
    ggplot(aes(x = x, y = .std.resid, 
             size = .cooksd, colour = .cooksd)) +
      geom_smooth(method = method) +
      geom_point() +
      geom_point(aes(color = .std.resid)) +  
      scale_color_gradient2(low = "blue", mid = "lightgrey", high = "red") +
      guides(color = F) +
      geom_segment(aes(x, .std.resid,
                   xend = x, 
                   yend = 0), 
                   alpha = .05) +
      #geom_text(aes(label = rownames(dat))) +
      scale_size_area("Cook’s distance") +
      guides(size = F) + 
      theme_minimal() +
      xlab("Unabhängige Variable X") + ylab("Standardisierte Residuen")

  } else{

    gg1 <- dat %>%
      ggplot(aes(x, .std.resid)) + 
      geom_point(aes(color = .std.resid)) +  
      scale_color_gradient2(low = "blue", mid = "lightgrey", high = "red") +
      guides(color = F, alpha = F) +
#  geom_segment(aes(x, .std.resid,
#                   xend = x, 
#                   yend = 0, 
#                   alpha = .2)) +
      geom_smooth(method = method) +
      xlab("Unabhängige Variable X") + ylab("Standardisierte Residuen") + 
      theme_minimal()

    if(type %in% c("curved.up", "curved.down")){
    gg1 <- gg1 + geom_smooth(method = "loess", color = "red")
    }
   }
  }
return(gg1)
}


```

## Ideal Linear

```{r}

plot_it("linear.up", n =2500, error = 2.5)

plot_it("linear.down", n =2500, error = 2.5)

```

## Quadratic

```{r pressure}

plot_it("curved.up", slope = 4, n =1000, error = 150)
plot_it("curved.down", slope = 4, n =1000, error = 150)

```

## Heteroskedastizität

```{r}

plot_it("curved.lowhigh", n = 2000, error = 2)
plot_it("fan.shaped", n = 2000, error = 2)

```

## Residuenabhängigkeit

```{r}

draw.data(type = "auto.corr") %>% 
    lmer(y ~ x + (x|col), data = .) %>%
    augment() %>% 
      ggplot(aes(x,y, colour = col)) + 
        geom_point()  + 
        geom_segment(aes(x, y,
                   xend = x, yend = .fitted)) +
        geom_line(aes(x, .fitted, colour = col)) +
#        geom_smooth(method = "lm", color = "black") +
        theme_minimal()

```

## Multikolinearität

```{r}
  
sim_data <- draw.data(type = "multicol")
  p1 <- sim_data  %>% 
     filter(term=="x1") %>% 
     ggplot(aes(cors, std.error, colour = n, group = n)) + 
     geom_smooth(method = "loess", se = F, size = 1, alpha = 0.5) +
     xlab("Korrelation") + ylab("log(Standardfehler X1)") + 
     theme_hc() + scale_color_viridis(direction = -1,
     #   limits = c(5, 3.5) * 1000, 
        breaks = c(0.1, 1.3, 2.5) * 1000, 
        labels = c("50", "1300", "3000")) +
     scale_y_log10()
  p2 <- sim_data  %>% 
     filter(term=="x1") %>% 
     ggplot(aes(cors, statistic, colour = n, group = n)) + 
     geom_smooth(method = "loess", se = F, size = 1, alpha = 0.5) +
     xlab("Korrelation") + ylab("t-Statistik X1") + 
     theme_hc() + scale_color_viridis(direction = -1,
     #   limits = c(5, 3.5) * 1000, 
        breaks = c(0.1, 1.3, 2.5) * 1000, 
        labels = c("50", "1300", "3000")) 
  
 gridExtra::grid.arrange(p1, p2, ncol = 2)

#p3 <- sim_data  %>% 
#     filter(term=="x1") %>% 
#     filter(n>200) %>% 
#     ggplot(aes(cors, estimate, colour = n, group = n)) + 
#     #geom_smooth(method = "loess", se = F, size = 1, alpha = 0.5) +#
#     geom_line(alpha = 0.5) +
#     xlab("Korrelation") + ylab("b-Koeffizient") + 
#     theme_hc() + scale_color_viridis(direction = -1) 

p4 <- sim_data  %>% 
     filter(term=="x1") %>% 
     filter(n>200) %>% 
     ggplot(aes(cors, std.estimate, colour = n, group = n)) + 
     #geom_smooth(method = "loess", se = F, size = 1, alpha = 0.5) +
     geom_line(alpha = 0.8) +
     xlab("Korrelation") + ylab("Standardisierter b-Koeffizient X1") + 
     theme_hc() + scale_color_viridis(direction = -1,
     #   limits = c(5, 3.5) * 1000, 
        breaks = c(0.6, 1.5, 2.5) * 1000, 
        labels = c("200", "1300", "3000")) + 
     geom_hline(yintercept = 0.125, linetype = "longdash") + 
     annotate("text", x = 0.08, y = 0.22, label = "Standardisiertes b = 0.125")
#p3
p4

# ggsave(p3, filename = "p3.png")
# ggsave(p4, filename = "p4.png")

 
```

## Ausreißer

```{r}
gg1 <- plot_it2(type="outlier", slope = 0.1, n=400, error = 6) + ylim(-15,20) + xlim(0,4) + stat_cor()

outliers <- data.frame(x = rnorm(100, 3.6, .15), 
                       y = rnorm(100, 18, 2))

gg2 <- plot_it2(type="outlier", slope = 0.1, n=400, error = 6, outlierdata =  outliers) + ylim(-15,20) + xlim(0,4) + stat_cor()

arranged <- grid.arrange(gg1, gg2, ncol = 2)

ggsave(arranged, filename = "Workshop - Regressionsdiagnostik/images/outlier.png", width = 10, height = 5)

# 
# outliers <- data.frame(x = rnorm(100, 3.6, .15), 
#                        y = rnorm(100, 40, 5))
# 
# plot_it2(type="outlier", slope = 3, n=500, error = 6, outlierdata = outliers) + ylim(-15,50) + xlim(0,4) + stat_cor()

#plot_it2(type="cooksd", slope = 0.1, n=400, error = 6) + xlim(0,4)

outliers <- data.frame(x = rnorm(20, 3.6, .15), 
                       y = rnorm(20, 18, 5))

plot_it2(type="cooksd", slope = 0.1, n=400, error = 6, outlierdata =  outliers) + xlim(0,4)

ggsave(filename = "Workshop - Regressionsdiagnostik/images/cooksd.png")

```

